version: "3"
services:
  couchserver:
    image: couchdb:3.3.2
    restart: always
    ports:
      - "5984:5984"
    networks:
      - localnetwork
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=password
    volumes:
      - ./dbdata:/opt/couchdb/data
      - ./local.ini:/opt/couchdb/etc/local.d/local.ini

networks:
  localnetwork:
    driver: bridge
